# -*- coding: utf-8 -*-
"""Untitled58.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGLQ5r3gpChNV0aW-r5WNx6iAdom81-Q
"""

import pandas as pd
import string
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

# Ensure necessary NLTK data is downloaded (run once)
import nltk
nltk.download('stopwords')
nltk.download('punkt_tab')

# Text Preprocessing Function
def process_text(text):
    """
    Removes punctuation and stopwords, and returns a list of clean words.
    """
    if text is None:
        return []
    # Remove punctuation

    # for char in text:
    #   if char not in string.punctuation:
    #     print(char)
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)

    # Remove stopwords
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    return clean_words