# -*- coding: utf-8 -*-
"""Untitled59.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLwwH_zzdlA1deBZzfAJC0715bk_h96X
"""

import subprocess
import time
import requests


def test_docker():

    # Build docker image
    subprocess.run(["docker", "build", "-t", "spam-flask", "."], check=True)

    # Run container in background
    subprocess.run(
        ["docker", "run", "-d", "-p", "5000:5000", "--name", "spam_test", "spam-flask"],
        check=True
    )

    # Give server time to start
    time.sleep(12)

    response = None

    try:
        response = requests.post(
            "http://127.0.0.1:5000/score",
            json={"text": "Congratulations! You won a free prize!"}
        )

        assert response.status_code == 200

        data = response.json()

        assert "prediction" in data
        assert "propensity" in data

    finally:
        time.sleep(2)   # allow request to finish
        # Stop and remove container
        subprocess.run(["docker", "stop", "spam_test"])
        subprocess.run(["docker", "rm", "spam_test"])