# -*- coding: utf-8 -*-
"""Untitled57.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqyHYubaLbrxEKHqavJ_qfF1hy3yvtWn
"""

#score.py has score function
from score import score
#best mlflow model uses process_text function
from preprocessing import process_text

from flask import Flask, request, jsonify
import joblib

# Initialize Flask app
app = Flask(__name__)

#get the best model
model = joblib.load("best_model.pkl")

THRESHOLD = 0.5


@app.route("/score", methods=["POST"])
def score_endpoint():
    # Get JSON data from request
    data = request.get_json()

    # Extract text
    text = data.get("text")



    # Call the score function
    prediction, propensity = score(
        text=text,
        model=model,
        threshold=THRESHOLD
    )

    # Return JSON response
    return jsonify({
        "prediction": int(prediction),
        "propensity": float(propensity)
    })

#Run the app
if __name__ == "__main__":
    app.run(debug=True)