# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOvRxlNzi1VNXsBpFQ5YNk0bq6HkUKgP
"""

import string
import sklearn
import numpy as np

# def score(text:str, model:sklearn.estimator, threshold:float):
def score(text:str, model:sklearn.base.BaseEstimator, threshold:float):

  #calculate propensity, but considering linearSVM that does not have .predict_proba
  if hasattr(model, "predict_proba"):
      propensity = model.predict_proba([text])[0][1]
  else:
      score = model.decision_function([text])[0]
      propensity = 1 / (1 + np.exp(-score))

  prediction = int(propensity >= threshold)
  return prediction, float(propensity)