# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qvVtnGdMDrc_XBg5zaIdwX-Qk3DrS7sA
"""

import joblib
import pandas as pd

#score.py has score function
from score import score
#best mlflow model uses process_text function
from preprocessing import process_text

def smoke_format_sanity_test(model):
    # Sample input text
    sample_text = "This is a test message."

    # Call score function
    prediction, propensity = score(
        text=sample_text,
        model=model,
        threshold=0.5
    )

    # Smoke test: just ensure it runs and returns something
    assert prediction is not None
    assert propensity is not None

    #Format test: ensure prediction value is integer and propensity is float
    assert type(prediction) == int
    assert type(propensity) == float

    #Sanity check
    assert prediction in [0, 1]
    assert 0 <= propensity <= 1

def edge_case_check(model):
    # Sample input text
    sample_text = "This is a test message."

    # Call score function at threshold 1
    prediction, _ = score(
        text=sample_text,
        model=model,
        threshold=1
    )

    assert prediction == 0

    # Call score function at threshold 0
    prediction, _ = score(
        text=sample_text,
        model=model,
        threshold=0
    )

    assert prediction == 1

def typical_input_check(model):
    # obvious spam
    text =  "URGENT! Congratulations! You have won a FREE jackpot prize. Click now and provide your credit card details and PIN to claim your reward."

    prediction, _ = score(
        text=text,
        model=model,
        threshold=0.5
    )

    assert prediction == 1

    # obvious non-spam

    text = "It's been a long time. Let's meet."

    prediction, _ = score(
        text=text,
        model=model,
        threshold=0.5
    )

    assert prediction == 0

def test_score():
  model = joblib.load("best_model.pkl")
  smoke_format_sanity_test(model)
  edge_case_check(model)
  typical_input_check(model)

def test_flask():
    from app import app

    app.testing = True
    client = app.test_client()

    response = client.post(
        "/score",
        json={"text": "This is a test message"}
    )

    assert response.status_code == 200

    data = response.get_json()

    assert "prediction" in data
    assert "propensity" in data
    assert isinstance(data["prediction"], int)
    assert isinstance(data["propensity"], float)
    assert data["prediction"] in [0, 1]
    assert 0 <= data["propensity"] <= 1